server {
    listen 80;
    listen [::]:80;
    server_name ip2region.io www.ip2region.io;

    location /.well-known/acme-challenge/ {
        root /www/wwwroot/ip2region.io;
    }

    return 301 https://cnip.io$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ip2region.io www.ip2region.io;
    root /www/wwwroot/ip2region.io;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/ip2region.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ip2region.io/privkey.pem;

    location /.well-known/acme-challenge/ {
        root /www/wwwroot/ip2region.io;
    }

    return 301 https://cnip.io$request_uri;
}
