/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IpTargetRouteImport } from './routes/ip.$target'
import { Route as DomainTargetRouteImport } from './routes/domain.$target'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpTargetRoute = IpTargetRouteImport.update({
  id: '/ip/$target',
  path: '/ip/$target',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainTargetRoute = DomainTargetRouteImport.update({
  id: '/domain/$target',
  path: '/domain/$target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/domain/$target': typeof DomainTargetRoute
  '/ip/$target': typeof IpTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/domain/$target': typeof DomainTargetRoute
  '/ip/$target': typeof IpTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/domain/$target': typeof DomainTargetRoute
  '/ip/$target': typeof IpTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docs' | '/domain/$target' | '/ip/$target'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs' | '/domain/$target' | '/ip/$target'
  id: '__root__' | '/' | '/about' | '/docs' | '/domain/$target' | '/ip/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  DomainTargetRoute: typeof DomainTargetRoute
  IpTargetRoute: typeof IpTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip/$target': {
      id: '/ip/$target'
      path: '/ip/$target'
      fullPath: '/ip/$target'
      preLoaderRoute: typeof IpTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$target': {
      id: '/domain/$target'
      path: '/domain/$target'
      fullPath: '/domain/$target'
      preLoaderRoute: typeof DomainTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  DomainTargetRoute: DomainTargetRoute,
  IpTargetRoute: IpTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
